## name 1 arg; variable w/parens
## failures 1
## cut

select( $fh );

#-----------------------------------------------------------------------------

## name 1 arg; variable, as built-in
## failures 1
## cut

select $fh;

#-----------------------------------------------------------------------------

## name 1 arg; fh, w/parens
## failures 1
## cut

select( STDERR );

#-----------------------------------------------------------------------------

## name 1 arg; fh, as built-in
## failures 1
## cut

select STDERR;

#-----------------------------------------------------------------------------

## name 4 args
## failures 0
## cut

select( undef, undef, undef, 0.25 );

#-----------------------------------------------------------------------------

## name RT Bug #15653
## failures 0
## cut

sub select { }

#-----------------------------------------------------------------------------

##############################################################################
#      $URL: http://perlcritic.tigris.org/svn/perlcritic/branches/Perl-Critic-backlog/t/InputOutput/ProhibitOneArgSelect.run $
#     $Date: 2009-02-15 11:10:42 -0600 (Sun, 15 Feb 2009) $
#   $Author: clonezone $
# $Revision: 3116 $
##############################################################################

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 78
#   indent-tabs-mode: nil
#   c-indentation-style: bsd
# End:
# ex: set ts=8 sts=4 sw=4 tw=78 ft=perl expandtab shiftround :
