## name RCS keywords in POD
## failures 0
## cut
=pod

  $Revision: 1467 $
  $Source$
  $Date: 2007-04-12 01:26:09 -0700 (Thu, 12 Apr 2007) $

=cut

#-----------------------------------------------------------------------------

## name No RCS keywords at all
## failures 3
## cut

#just a comment
$foo = "bar";
$baz = qq{nuts};

#-----------------------------------------------------------------------------

## name Keywords in comments
## failures 0
## cut
# $Revision: 1467 $
# $Source$
# $Date: 2007-04-12 01:26:09 -0700 (Thu, 12 Apr 2007) $

#-----------------------------------------------------------------------------

## name Id in comments
## failures 0
## cut
# $Id$
END_PERL

#-----------------------------------------------------------------------------

## name Keywords in literals
## failures 0
## cut
'$Revision: 1467 $'
'$Source: foo/bar $'
'$Date: 2007-04-12 01:26:09 -0700 (Thu, 12 Apr 2007) $'

#-----------------------------------------------------------------------------

## name Keywords in literals, q{}-style
## failures 0
## cut
q{$Revision: 1467 $}
q{$Source: foo/bar $}
q{$Date: 2007-04-12 01:26:09 -0700 (Thu, 12 Apr 2007) $}

#-----------------------------------------------------------------------------

## name Keywords in literals, q{}-style, with parms
## failures 0
## parms {keywords => 'Revision Author Id'}
## cut
q{$Revision: 1467 $}
q{$Author: thaljef $}
q{$Id: whatever $}

#-----------------------------------------------------------------------------

## name Empty code
## failures 1
## parms {keywords => 'Author Id'}
## cut
#nothing here!
$policy = 'Miscellanea::RequireRcsKeywords';
is( pcritique($policy, \$code, \%config), 1, $policy);

