## name sleep, as list
## failures 1
## cut

select( undef, undef, undef, 0.25 );

#-----------------------------------------------------------------------------

## name sleep, as list w/var
## failures 1
## cut

select( undef, undef, undef, $time );

#-----------------------------------------------------------------------------

## name sleep, as built-in
## failures 1
## cut

select undef, undef, undef, 0.25;

#-----------------------------------------------------------------------------

## name select on read
## failures 0
## cut

select $vec, undef, undef, 0.25;

#-----------------------------------------------------------------------------

## name select on write
## failures 0
## cut

select undef, $vec, undef, 0.25;

#-----------------------------------------------------------------------------

## name select on error
## failures 0
## cut

select undef, undef, $vec, 0.25;

#-----------------------------------------------------------------------------

## name select as word
## failures 0
## cut

$foo{select};

#-----------------------------------------------------------------------------

##############################################################################
#      $URL: http://perlcritic.tigris.org/svn/perlcritic/tags/Perl-Critic-0.22/t/BuiltinFunctions/ProhibitSleepViaSelect.run $
#     $Date: 2006-12-16 22:33:36 -0800 (Sat, 16 Dec 2006) $
#   $Author: thaljef $
# $Revision: 1103 $
##############################################################################

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 78
#   indent-tabs-mode: nil
#   c-indentation-style: bsd
# End:
# ex: set ts=8 sts=4 sw=4 tw=78 ft=perl expandtab :
