## name glob via <...>
## failures 1
## cut

@files = <*.pl>;

#-----------------------------------------------------------------------------

## name glob via <...> in foreach
## failures 1
## cut

foreach my $file (<*.pl>) {
    print $file;
}

#-----------------------------------------------------------------------------

## name Multiple globs via <...>
## failures 1
## cut

@files = (<*.pl>, <*.pm>);

#-----------------------------------------------------------------------------

## name I/O
## failures 0
## cut

while (<$fh>) {
    print $_;
}

#-----------------------------------------------------------------------------

##############################################################################
#      $URL: http://perlcritic.tigris.org/svn/perlcritic/branches/Perl-Critic-1.073/t/BuiltinFunctions/RequireGlobFunction.run $
#     $Date: 2006-11-27 07:47:36 -0600 (Mon, 27 Nov 2006) $
#   $Author: clonezone $
# $Revision: 977 $
##############################################################################

# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 78
#   indent-tabs-mode: nil
#   c-indentation-style: bsd
# End:
# ex: set ts=8 sts=4 sw=4 tw=78 ft=perl expandtab :
