##############################################################################
#      $URL: http://perlcritic.tigris.org/svn/perlcritic/trunk/Perl-Critic/t/RegularExpressions/ProhibitComplexRegexes.run $
#     $Date: 2007-10-04 06:39:10 -0500 (Thu, 04 Oct 2007) $
#   $Author: chrisdolan $
# $Revision: 1963 $
##############################################################################

## name basic passes
## failures 0
## cut

m/foo/;
m/foo foo foo foo foo foo foo foo foo foo foo foo/;
m/foo
  foo/;

m/foo # this is a foo
  bar # this is a bar
  baz # this is a baz
  more # more more more more more
 /x;

m/





/;

#-----------------------------------------------------------------------------

## name basic failures
## failures 1
## cut

m/ foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo foo/;

## name basic failures, m//x
## failures 1
## optional_modules Regexp::Parser
## cut

m/foo # this is a foo
  bar # this is a bar
  baz # this is a baz
  1234567890 1234567890 1234567890 1234567890 1234567890 1234567890 # this is too long
 /x;

#-----------------------------------------------------------------------------

## name config
## failures 1
## parms {max_characters => 2}
## cut

m/ foo /;

#-----------------------------------------------------------------------------

## name config errors
## failures 0
## parms {max_characters => 'two'}
## cut

m/ foo /;

#-----------------------------------------------------------------------------

## name config errors
## failures 0
## parms {max_characters => 0}
## cut

m/ foo /;

#-----------------------------------------------------------------------------

## name failing regexp with syntax error
## failures 0
## cut

m/foofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoofoo(/x;

#-----------------------------------------------------------------------------
# Local Variables:
#   mode: cperl
#   cperl-indent-level: 4
#   fill-column: 78
#   indent-tabs-mode: nil
#   c-indentation-style: bsd
# End:
# ex: set ts=8 sts=4 sw=4 tw=78 ft=perl expandtab :
